### ISSUE TITLE
Choose a storage system and stick to it

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#143]
Currently (v0.2) Oxigraph provides 3 storage systems (RocksDB, Sled and in memory). This is a challenge for Oxigraph development and leads to fragmentation in Oxigraph usages (some instances are using RocksDB, other Sled). In March we had a discussion about using only Sled for storage in Oxigraph 0.3 (#89) and the current development branch (v0.3) has been migrated to it.

However, since March, Sled 1.0 version seems to have been postponed to an unknown date and [development speed has also slow down signficiantly](https://github.com/spacejam/sled/graphs/code-frequency). So, it might not be the best bet. I see 4 possibles alternatives:
1. Stick to Sled, taking the risk that it might get unmaintained and planned storage compatiblity break between the current released version and the work-in-process v1.0.
2. Keep RocksDB (slightly slower read than Sled, very slow build time, requires a C++ compiler).
3. Use LMDB (no concurrent writes, requires a C compiler, not tested and benchmarked yet as part of Oxigraph).
4. Develop our own storage system customized for Oxigraph use (lots of work and possible bugs).

**Comment by igor-krawczuk** [comment]
Chiming in as a (new) user I'd vote  for rocksdb for stability and portability. Clang isn't too bad a dependency and since this is rust slow build times are gonna be a problem anyway. And without knowing the internals, rocksdb being a generic key-value store should make it feasible to implement an internal storage abstraction layer and switch to Sled/another KV store if it becomes a true painpoint?

**Comment by Tpt** [comment]
I have just released [v0.3.0-beta.1](https://github.com/oxigraph/oxigraph/releases/tag/v0.3.0-beta.1) that sticks to RocksDB for stability and features.
