### ISSUE TITLE
Support for Group_By

### ISSUE THREAD

**Issue by macgrs** [oxigraph/oxigraph#208]
Hey !

I successfully set up a local oxigraph server with the docker-compose and loaded it with _SKOS-based Thesaurii_ using the RDFStore interface.

I've got a weird `group by` bad request issue with a basic `group by` query. I can't state if that's a special working case for my _rdflib-endpoint_ or an oxigraph issue (or a mere sparql typo, which would be shameful).

Query : 
```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
prefix litho:  <https://data.geoscience.fr/ncl/litho>

SELECT DISTINCT ?c ?label ?description 
(group_concat(distinct ?narroweruri ; separator = ",") AS ?gnarrowuris)
WHERE {
  ?cs skos:notation "litho" .
  ?c a skos:Concept . 
  FILTER(STRSTARTS(STR(?c), STR(?cs))) .
  
  ?c skos:notation "899" .
  ?c skos:prefLabel ?label .
  
  ?c skos:narrower ?narroweruri .
}
group by ?c
```

From the _rdflib-endpoint_, the response is the following table (expected output) :
|c                                       |label    |gnarrowuris|
|----------------------------------------|---------|-----------|
|https://data.geoscience.fr/ncl/litho/899|Gabbroïde|https://data.geoscience.fr/ncl/litho/348,https://data.geoscience.fr/ncl/litho/129,https://data.geoscience.fr/ncl/litho/349,https://data.geoscience.fr/ncl/litho/364,https://data.geoscience.fr/ncl/litho/366,https://data.geoscience.fr/ncl/litho/347,https://data.geoscience.fr/ncl/litho/117,https://data.geoscience.fr/ncl/litho/133,https://data.geoscience.fr/ncl/litho/132,https://data.geoscience.fr/ncl/litho/135,https://data.geoscience.fr/ncl/litho/335,https://data.geoscience.fr/ncl/litho/114,https://data.geoscience.fr/ncl/litho/344,https://data.geoscience.fr/ncl/litho/332,https://data.geoscience.fr/ncl/litho/157,https://data.geoscience.fr/ncl/litho/351,https://data.geoscience.fr/ncl/litho/155,https://data.geoscience.fr/ncl/litho/139,https://data.geoscience.fr/ncl/litho/343,https://data.geoscience.fr/ncl/litho/960|

From the oxygraph server, I've got this 400-BAD REQUEST unbounded variable error :
`error at 17:12: expected one of "$", "(", ":", "<", "?", IF, TZ, The SELECT contains a variable that is unbound, ['0' ..= '9' | '\u{00B7}' | '\u{0300}' ..= '\u{036F}' | '\u{203F}' ..=
'\u{2040}'], ['A' ..= 'Z' | 'a' ..= 'z' | '\u{00C0}' ..= '\u{00D6}' | '\u{00D8}' ..=
'\u{00F6}' | '\u{00F8}' ..= '\u{02FF}' | '\u{0370}' ..= '\u{037D}' |
'\u{037F}' ..= '\u{1FFF}' | '\u{200C}' ..= '\u{200D}' | '\u{2070}' ..=
'\u{218F}' | '\u{2C00}' ..= '\u{2FEF}' | '\u{3001}' ..= '\u{D7FF}' |
'\u{F900}' ..= '\u{FDCF}' | '\u{FDF0}' ..= '\u{FFFD}'], ['_'], [_]`

Thanks in advance for the troubleshoot,
A lot of cheers for this project

**Comment by afs** [comment]
The problem is the SELECT using variables that are not in-scope outside the GROUP BY. Only group keys and aggregates are in-scope after GROUP BY and can then be used in the SELECT clause. `?description` is also a problem.

For each value of `?c`, the group-bu forms a set of values for `?label` so there isn't a single value for `?label`. IIRC RDFLib behaves as if `SELECT ... SAMPLE(?label) ...` was used -- `SAMPLE` is an aggregate that picks on value, no spec guarantee of which.

In the SPARQL 1.1 spec:
* https://www.w3.org/TR/sparql11-query/#aggregateRestrictions
* https://www.w3.org/TR/sparql11-query/#variableScope

You can try it online at http://www.sparql.org/query-validator.html -- the parser is completely separate from Oxigraph. It also reports an error.

**Comment by Tpt** [comment]
@macgrs Thank you for trying Oxigraph! Indeed, the SPARQL parser messages are currently very bad (there is #129 about it).
The key part of the error message is "The SELECT contains a variable that is unbound". As @afs explained (@afs thank you so muuch for your reply) the `?label` and `?description` in the `SELECT` part should also be in the `GROUP BY` clause or be aggregate expressions like `GROUP_CONCAT` or `SAMPLE` to be valid. Because in the current query the evaluator has no way to know how a value for these variables should be assigned per group (a random one like rdflib, the min/max one, the first one...).

**Comment by macgrs** [comment]
Thank you, gentlemen, for your developed and quick anwser, that was the shameful typo here :/

> IIRC RDFLib behaves as if SELECT ... SAMPLE(?label) ... was used -- SAMPLE is an aggregate that picks on value, no spec guarantee of which.

So all my queries are incomplete/invalid, I will be more steady using the validator !

Bests,

**Comment by MadsHolten** [comment]
I know this post is closed, but I have an addition. GROUP_BY doesn't work with URIs. Only literal values. Of course you can just bind to a string and use that var instead, but for me it was strange since the query that works on other triplestores didn't give the expected results in Oxigraph.

BTW it's the first time I try Oxigraph and so far I am pretty impressed!

**Comment by Tpt** [comment]
@MadsHolten Hi! Thank you for trying Oxigraph. Sorry for the issue. Do you have a query that does not seems to work? I have tried the following one and it seems to work properly:
```sparql
PREFIX ex: <http://example.org/>
SELECT ?s (COUNT(*) AS ?c) WHERE {
  VALUES (?s ?o) {
    (ex:s1 ex:o11)
    (ex:s1 ex:o12)
    (ex:s2 ex:02)
  }
} GROUP BY ?s
```
