### ISSUE TITLE
Support GROUP_CONCAT function

### ISSUE THREAD

**Issue by luowei-D** [oxigraph/oxigraph#33]
use group by and GROUP_CONCAT function in sparql, but only the columns in the "group by"  return results

**Comment by Tpt** [comment]
Hi! Sorry for this problem. Do you have an example of query that does not work properly to help me investigate?

**Comment by luowei-D** [comment]
This code will work on protege, but failed in oxigraph.I use RocksDbStore to prepare_query and exec, but only the columns in the "group by" return results

`PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX test: <http://test.com/test/#>
SELECT ?host ?service ?d ?ip (GROUP_CONCAT(?host_event) as ?event )
WHERE { 
    ?host rdf:type test:Host  .
    ?service test:live ?host .
    ?host test:ip ?ip .
    OPTIONAL {
      ?service test:depend ?d .
    }
    OPTIONAL {
       ?host test:has_event ?host_event
    }
}
GROUP BY ?host ?service ?d ?ip
`

**Comment by Tpt** [comment]
Thank you for the query!

The bug happened because the code was setting the return value of `GROUP_CONCAT` to null as soon as a concatenated value is also null. Such null values where happening in your query because of the `OPTIONAL`s. I have changed the behavior to ignore null values and added a test.

On a completely different topic, I have also pushed a change that improves the API to handle SPARQL results, allowing to directly iterate on `BindingsIterator` and get nice `QuerySolution` objects that allows to easily get values for a given variable name. I have updated the examples in the documentation comments.
