### ISSUE TITLE
Replace Rocksdb with Speedb

### ISSUE THREAD

**Issue by ansarizafar** [oxigraph/oxigraph#374]
Speedb is 100% compatible with Rocksdb. The performce/efficiency difference between Rocksdb and Speedb is quite big and Speedb also solves some of Rocksdb issues.
It is worth the effort to replace Rocksdb with Speedb.

https://www.youtube.com/watch?v=CMpB8AyHwvI&feature=youtu.be
https://www.speedb.io/

**Comment by Tpt** [comment]
@ansarizafar Hi! Thank you for suggesting it. The storage engine is a key part of Oxigraph and Oxigraph maintenance is quite under-resourced at the moment. I am feeling scared to spend "innovation points" on changing storage engine to one I am not sure it will be maintained long term wise whereas RocksDB is currently well maintained and is likely to keep being maintained in the long term because of the big projects depending on it (MyRocks, TiKV...).
