### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by maxlath** [oxigraph/oxigraph#40]
Dear Thomas,

To make it easier for people unfamiliar with the project dependencies to try oxigraph, I wrote a [Dockerfile](https://github.com/maxlath/docker-oxigraph/blob/master/Dockerfile) to generate images, and published those as [maxlath/oxigraph](https://hub.docker.com/r/maxlath/oxigraph) and [maxlath/oxigraph-wikibase](https://hub.docker.com/r/maxlath/oxigraph-wikibase).

If you're interested, I could give ownership of the [repo](https://github.com/maxlath/docker-oxigraph) to the oxigraph organization and republish the images as `oxigraph/oxigraph` and `oxigraph/oxigraph-wikibase`, what do you think?

Au plaisir

**Comment by Tpt** [comment]
Hi Maxime!

It's a great idea. Instead of having a different repository for the Docker images, we could maybe just have them in this main git repository. This way, we could easily release new Docker images when a new release is done (maybe using GitHub CI).
What do you think about it?

**Comment by maxlath** [comment]
Sounds great! I opened a PR in this sense #41

I'm not very familiar with GitHub CI: could it just run the `publish_docker_images.sh` script as such, given some credentials?

I didn't try Oxigraph for JavaScript yet, but will do ;)

**Comment by Tpt** [comment]
I have published the Docker images to [Docker hub](https://hub.docker.com/orgs/oxigraph/repositories). I have tweaked the `Dockerfile` to build from the local code instead of doing a `git clone`. I have just to setup GitHub Actions to[ publish the images automatically](https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images) when a release is done.

**Comment by Tpt** [comment]
The publication is now automated with Github actions. Let's close this issue
