### ISSUE TITLE
SPARQL TSV result: the case of queries with 0 result columns (`SELECT * WHERE {}`)

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#406]
The [IANA TSV grammar](https://www.iana.org/assignments/media-types/text/tab-separated-values) requires at least one column in the TSV file.

However, the [SPARQL TSV result format](https://www.w3.org/TR/sparql11-results-csv-tsv/) should be able to serialize the without-columns query  `SELECT * WHERE {}`. There is an incompatibility between the two.

I see two options:
1. extend a bit the TSV syntax to support the "empty query" case, serialized using `\n\n`.
2. forbid to serialize to TSV this query.

I would tend to favor option 1 that seems fairly clean to me.

**Comment by Tpt** [comment]
@afs Sorry for reaching out to you, I believe you might already have an opinion about this problem or be interested in it.

**Comment by afs** [comment]
The TSV spec shows it's SQL background.

I think option 1 is the way to treat this.

It is for small result sets (a very large `SELECT * { {} UNION {} UNION ... }` doesn't seem very likely!)

If the client TSV parse can cope, we cover a possibility that otherwise would be a 400 error.
If the client TSV parser fails, there wasn't a way of sending the results and failing client side on a small document isn't too bad.

Raised as an issue on the CSV/TSV results document.
w3c/sparql-results-csv-tsv#9

**Comment by Tpt** [comment]
@afs thank you for your feedback and for opening an issue on the CSV/TSV document!

I have added tests for option 1 in Oxigraph.
