### ISSUE TITLE
Distribute on crates.io

### ISSUE THREAD

**Issue by alexkreidler** [oxigraph/oxigraph#44]
I understand that this is a work in progress project, but I think the earlier people can experiment, the better! Maybe just release it with a less than 1.0 version.

Also, it would put the documentation on Docs.rs, which could be useful. I think a release could also attract more contributors.

**Comment by Tpt** [comment]
Hi @alexkreidler! I'm actually preparing a release. The documentation is ready. I'm finishing some big changes in the storage system and I plan to push it just after. It should be out in a few days.

**Comment by Tpt** [comment]
I have pushed today a first release: https://crates.io/crates/oxigraph
It's a "RC" version because I was not sure that the process would work.
Everything worked fine except the automated Docker build.
I am currently improving the documentation (especially on the Python side) and running benchmarks before pushing the real 0.1 in the next few days.

**Comment by alexkreidler** [comment]
Great, I'll close this issue!
