### ISSUE TITLE
Build of Oxigraph for JS is failing

### ISSUE THREAD

**Issue by Tpt** [oxigraph/oxigraph#86]
The build of Oxigraph for JS has started to fail in February 19th. I am not sure what is the cause of this problem, both failing and passing builds are using Rust 1.50 stable and wasm-pack 1.9.1.

I have reported this issue to [wasm-pack](https://github.com/rustwasm/wasm-pack/issues/981) .

**Comment by mlipke** [comment]
Hi, I was trying out oxigraph over the weekend and I stumbled upon this bug. I looked at the wasm-objdump and I think I found the root cause: at some point `quick-xml::escape::unescape()` declares about 75000 (!) locals which far exceeds the [limit](https://github.com/v8/v8/blob/master/src/wasm/wasm-limits.h#L40) in v8 for wasm function locals (and other engines have similar limits I think). This causes `wasm-pack` to fail when parsing the module.
```
au94cf func[28670] <_ZN9quick_xml7escapei8unescape17heccca164dc916471E>:
 a094d0: 68 7f                      | local[0..103] type=i32
 a094d2: 01 7e                      | local[104] type=i64
 a094d4: 0c 7f                      | local[105..116] type=i32
 a094d6: 01 7e                      | local[117] type=i64
 a094d8: 03 7f                      | local[118..120] type=i32
 a094da: 01 7e                      | local[121] type=i64
 a094dc: 09 7f                      | local[122..130] type=i32
 a094de: 01 7e                      | local[131] type=i64
 a094e0: 26 7f                      | local[132..169] type=i32
 a094e2: 01 7e                      | local[170] type=i64
 a094e4: 06 7f                      | local[171..176] type=i32
 a094e6: 01 7e                      | local[177] type=i64
 a094e8: 06 7f                      | local[178..183] type=i32
 a094ea: 01 7e                      | local[184] type=i64
 a094ec: 03 7f                      | local[185..187] type=i32
 a094ee: 01 7e                      | local[188] type=i64
 a094f0: 15 7f                      | local[189..209] type=i32
 a094f2: 01 7e                      | local[210] type=i64
 a094f4: b6 ce 04 7f                | local[211..75784] type=i32
 a094f8: 01 7e                      | local[75785] type=i64
 a094fa: 03 7f                      | local[75786..75788] type=i32
 a094fc: 01 7e                      | local[75789] type=i64
 a094fe: 03 7f                      | local[75790..75792] type=i32
 a09500: 01 7e                      | local[75793] type=i64
 a09502: 02 7f                      | local[75794..75795] type=i32
```
See line starting with `a094f4`.

Going further up the chain, I think this behaivour was introduced in `quick-xml` sometime between release `0.20.0`, and `0.21.0`. `rio = "0.5.2"` is the first version that uses `quick-xml = "0.2.1"`. If I pin `rio_xml = "=0.5.1"` in oxigraph the build runs again.

Disclaimer: I am a Rust and wasm newbiew and this is what I found after googling around for a few hours. I followed the instructions in [this blog post](https://ritik-mishra.medium.com/resolving-the-wasm-pack-error-locals-exceed-maximum-ec3a9d96685b) for `wasm-objdump`. Running the build with `opt-level = 1` also seems to work.

**Comment by Tpt** [comment]
Thank you so much for this investigation.

This is caused by [this huge match that has been introduced in `quick-xml` 0.21](https://github.com/tafia/quick-xml/commit/1961d8e36e120cd439a4c91156b704072014da87). `quick-xml` 0.22 fixes the problem by hiding this `match` behind a feature. I have released a new version of `rio-xml` that depends on `quick-xml` 0.22.
New WASM compilation of Oxigraph should now work.
