### ISSUE TITLE
TermRef::Triple should expect a TripleRef rather than a &Triple

### ISSUE THREAD

**Issue by pchampin** [oxigraph/oxigraph#884]
**Is your feature request related to a problem? Please describe.**
A good thing about `NamedNodeRef` and `LiteralRef` (as opposed to `&NamedNode` or `&Literal`) is that they don't require me to actually build an instance of `NamedNode` or `Literal`, as long as the `...Ref` type can *refer* to valid data *as if* it was held by a `NamedNode` or `Literal`.

But this reasoning falls short with `TermRef`, because the `Triple` variant expects a `&Triple`, so I can not, in the general case, create a `TermRef` unless I have a real `Term` backing it.

**Describe the solution you'd like**
If `TermRef::Triple` was expecting `TermRef` instead of `&Term`, I could create a `TermRef` from valid data, without requiring to build a full `Term`.

**Describe alternatives you've considered**
I didn't think of any.

**Additional context**
This would be helpful in the Oxigraph-Sophia bridge: this would allow me to consistently build a `TermRef` from Sophia's `SimpleTerm` without additional conversion or allocation.

**Comment by Tpt** [comment]
Thank you for raising this issue!

The tricky thing is that if we use a `TripleRef` directly then `TripleRef` becomes a recursive structure because `TripleRef.object` is a `TermRef` and `TermRef::Triple` variant now contains a `TripleRef`. So, we would have to introduce a `Box` somewhere. The better choice here is likely having `TripleRef::Triple(Box<TripleRef>)` to only pay the `Box` cost for quoted triples. And, in this case, it means `Triple::as_ref` would have to allocate the box, making it expensive while not allowing other users like Sophia to avoid all allocations because of the `Box`.
Hence, the current choice of having a fast `Triple::as_ref` at the cost of making it a bit harder for Sophia.

But I am happy to revisit this if you think of something better.

**Comment by pchampin** [comment]
Ok, I get it. Thanks for your detailed response.
If I remember correctly (I need to check my code), I can make it work with Sophia, at the cost of allocating the new `Triple`.
But this seems to be a better tradeoff than inducing the cost (that you describe above) everywhere else.

I'm happy to close this issue, then.
