### ISSUE TITLE
INSERT/DELETE data limits update size?

### ISSUE THREAD

**Issue by bigerl** [oxigraph/oxigraph#892]
**Describe the bug**

I've been running a benchmark with v0.3.22 that includes updates of increasing sizes (10^1 to 10^6 triples). From  10^4 triples upwards, oxigraph gives me a 400 Bad Request. 

**To Reproduce**
Start oxigraph instance locally and post the attached [10k_ins_data.sparql](https://github.com/user-attachments/files/15822333/10k_ins_data.sparql.zip) with:
```
curl -X POST "http://your-sparql-endpoint-url" \
     -H "Content-Type: application/sparql-update" \
     --data-binary "@10k_ins_data.sparql"
```

**Question**

Is this intended behavior? Are there any configuration parameters to change this? Ideally, without rebuilding the oxigraph binary.

**Comment by Tpt** [comment]
Thank you for the great bug report!

Yes, Oxigraph buffers the SPARQL string in memory and then apply the update in a transactional way. There is a limit set on the maximum size of the SPARQL update. To load a lot of data, I would suggest to use a specialized endpoint like:

```
curl -f -X POST -H 'Content-Type:application/n-triples'  -T MY_FILE.nt "http://localhost:7878/store?default&no_transaction"
```

This limitation is because my guess is that people tend to have small update strings but load large RDF files. But maybe I am wrong and there are real world use case for big SPARQL update strings. Have you tried this update just do run some benchmarking or is there a real use case behind it?

**Comment by bigerl** [comment]
Thank you for the quick answer. 
The design decision sounds reasonable. I guess it is then a compile-time limit for the size of the buffer storing the SPARQL update string, right?

To answer your question: I was sending this request for benchmarking purposes only and do not target any specific downstream use-case at the moment.

**Comment by Tpt** [comment]
Yes! It is [a compile-time constant](https://github.com/oxigraph/oxigraph/blob/e249665234219ea98f537fb01d466dfe45c3575f/cli/src/main.rs#L36C1-L36C47).

Thank you! So, I guess the limit is still fine to have.

**Comment by bigerl** [comment]
So, not a bug but a feature. I am closing this.
