### ISSUE TITLE
Pagination: Linear growth of execution time with LIMIT / OFFSET 

### ISSUE THREAD

**Issue by nikokaoja** [oxigraph/oxigraph#917]
@Tpt great work with oxigraph, I have been using it extensively for more than a year.

Recently I've needed to traverse very large graph by querying batches of instances (where instance === set of triples defining an instance of specific class === subgraph).

I've ran experiment where I have:
- 50 000 instances
- or 3 400 000 triples (1 instance === 68 triples)

I've queried these instances in batches of 1000 using `CONSTRUCT` query with `LIMIT` and `OFFSET`, where:
- LIMIT was set to 1000
- while OFFSET was moved from 0 to 49 000

The result of given experiment one can see here:

![image](https://github.com/user-attachments/assets/00583624-57c7-43bf-b25c-3c0e706b8628)

As you can see there is continuous growth of query time for a batch of 1000 instances === 68000 triples.

Is this to be expected?

Any suggestion how I can alleviate this issue?

**Comment by nikokaoja** [comment]
Seems that the best way to accomplish my work is to use `DESCRIBE` and iterate over an array of Instance ids , as I have mean query time of 1.35 ms.

**Comment by Tpt** [comment]
> @Tpt great work with oxigraph, I have been using it extensively for more than a year.

Thank you!

> Is this to be expected?

Sadly yes. Oxigraph relies on RocksDB that does not allow to skip a given number of values (skipping a number of values does not plays well with [LSMTs](https://en.wikipedia.org/wiki/Log-structured_merge-tree)). Hence, when evaluating a query with an `OFFSET`, the evaluator can't actually skip and still have to iterate on the skipped results.

However, Oxigraph is currently quite naive in the way skipping is implementing, the evaluator will build the skipped intermediate results before discarding them instead of just ignoring what RocksDB returns. Hence it will do a lot of wasteful work. If we fix that, it should be possible with a bit of work to get much faster results (but sadly, with still a linear slowdown).

> Any suggestion how I can alleviate this issue?

Depending on the queries, Oxigraph might not have to construct the full result set into memory and will just stream the results back. So, doing a single query without `LIMIT` and `OFFSET` might work.

**Comment by nikokaoja** [comment]
@Tpt thanks for comprehensive answer. I will report back how my experimentation is going.

**Comment by nikokaoja** [comment]
`DESCRIBE` ended up as [the choice](https://github.com/cognitedata/neat/blob/dbfd31d645a348fdd0712974e0dc305caa6913ec/cognite/neat/graph/queries/_base.py#L970) leading to about 2 ms/instance speed which is for our use-case more than enough. Still a lot to gain by moving from sequential to parallel SPARQL queries.
