### ISSUE TITLE
use default prefix for "bare" curie in turtle serialization

### ISSUE THREAD

**Issue by jonassmedegaard** [oxigraph/oxigraph#993]
I like to write my turtle data compactly, using `@base` and @prefix`, like this:
```turtle
@base <https://purl.org/learn/0.1.1/> .
@prefix : <tentacular#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

: a owl:Ontology ;
        skos:prefLabel
                "Tentacular Learning Ontology"@en ,
                "Ontologi om tentakulær læring"@da .

<core#> a owl:Ontology .

<bisected#> a owl:Ontology ;
        skos:prefLabel
                "Bisected Learning Ontology"@en ,
                "Ontologi om tvedelt læring"@da .
```

When I do an `oxigraph convert` from turtle to turtle for a dataset, it recognizes the `@prefix` (nice! some tools loose that) but it looses the `@base` (which I guess is a sensible default, but I find in odd that I can only provide `--from-base` but not `--to-base`) and it does not make use of `@prefix` for the initial standalone `:`, leading to needlesly "blowing up" the output dataset:
```turtle
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix : <https://purl.org/learn/0.1.1/tentacular#> .
<https://purl.org/learn/0.1.1/tentacular#> a owl:Ontology ;
        skos:prefLabel "Tentacular Learning Ontology"@en , "Ontologi om tentakulær læring"@da .
<https://purl.org/learn/0.1.1/core#> a owl:Ontology .
<https://purl.org/learn/0.1.1/bisected#> a owl:Ontology ;
        skos:prefLabel "Bisected Learning Ontology"@en , "Ontologi om tvedelt læring"@da .
```

Should I file a separate wishlist request about lack of `--base-to` option?

Would also be nice to tell that I want TAB for indentation.

And would be cool with an option to newline+double-indent strings, as that tremendously enhances readability in my experience.

**Comment by Tpt** [comment]
Thank you for this feature request! This is very welcome.

If I try to split it up into parts:

- [ ]  Have a `relativize` method in `oxiri` that does the inverse of `resolve` i.e. from an absolute IRI and a base IRI return a relative IRI.
- [ ] Allow to inject a base IRI in the Turtle and TriG serializers in order to use the `relativize` method to print relative IRIs and a `@base` instruction at the beginning.
- [ ] Make `oxigraph convert` propagate the input base IRI to the output serializer just like for prefixes.
- [ ] Add to `oxigraph convert` a `--to-base` option to select a base IRI for the output.
- [ ] Make sure the Turtle/TriG can rewrite `<http://example.com#>` into `:` if `@prefix : <http://example.com#>` is given.

I tend to think only the `relativize` method needs a bit of work to be done properly, the other items seem quite easy.

**Comment by jonassmedegaard** [comment]
I have no idea how challenging this is, but am delighted that it sounds achievable to you :-)

**Comment by Tpt** [comment]
Done in v0.4.2
